import { describe, it, expect } from 'vitest';

/**
 * Task 4.3: Verify metadata is correct
 * 
 * This test verifies that the HTML metadata in the production build
 * contains the correct Camiprint branding and does NOT contain
 * any remnants of the Next.js template.
 * 
 * **Validates: Requirements 2.2**
 */
describe('Metadata Verification', () => {
  it('should have correct title tag', async () => {
    const response = await fetch('http://localhost:3000');
    const html = await response.text();
    
    // Extract title
    const titleMatch = html.match(/<title>(.*?)<\/title>/);
    expect(titleMatch).toBeTruthy();
    
    const title = titleMatch![1];
    
    // Verify title contains Camiprint branding
    expect(title).toContain('Camiprint');
    expect(title).toContain('Camisetas laborales y publicitarias');
    
    // Verify exact title
    expect(title).toBe('Camiprint | Camisetas laborales y publicitarias');
  });

  it('should have correct meta description', async () => {
    const response = await fetch('http://localhost:3000');
    const html = await response.text();
    
    // Extract meta description
    const descMatch = html.match(/<meta name="description" content="(.*?)"/);
    expect(descMatch).toBeTruthy();
    
    const description = descMatch![1];
    
    // Verify description is about Camiprint business
    expect(description).toContain('camisetas');
    expect(description).toContain('negocios');
    expect(description).toContain('restaurantes');
    expect(description).toContain('empresas');
  });

  it('should NOT contain Next.js template metadata', async () => {
    const response = await fetch('http://localhost:3000');
    const html = await response.text();
    
    // Verify NO template content in metadata
    expect(html).not.toContain('Create Next App');
    expect(html).not.toContain('Generated by create next app');
    expect(html).not.toContain('create-next-app');
  });

  it('should have correct favicon reference', async () => {
    const response = await fetch('http://localhost:3000');
    const html = await response.text();
    
    // Verify favicon link exists
    const faviconMatch = html.match(/<link rel="icon" href="(.*?)"/);
    expect(faviconMatch).toBeTruthy();
    
    const faviconHref = faviconMatch![1];
    
    // Verify it points to the correct favicon
    expect(faviconHref).toContain('/favicon.ico');
  });

  it('should have correct language attribute', async () => {
    const response = await fetch('http://localhost:3000');
    const html = await response.text();
    
    // Verify html lang attribute is Spanish
    const langMatch = html.match(/<html[^>]*lang="(.*?)"/);
    expect(langMatch).toBeTruthy();
    
    const lang = langMatch![1];
    expect(lang).toBe('es');
  });
});
